### ISSUE TITLE
Does not convert existing docstrings

### ISSUE THREAD

**Issue by karimbahgat** [dadadel/pyment#15] opened 2015-05-28 18:04 UTC
Hi Dadadel,

I am really happy to have come across your package here, a really great idea and feat on your end! I am very excited to start using it, specifically for converting Google docstrings to reST. 

But for some reason pyment refuses to convert existing Google docstrings. It just keeps the Google docstrings unchanged in place and adds reST parameters with their default values at the end (In your README you show that existing docstrings will be converted into the new format). I am on a Windows 8, and 32 bit Python 2.7, using pyment's v0.3 release. 

I tried many different ways, and I even tried to run the same test example from your README with the following script in the Python IDLE, with the executing code inside a `__main__` clause. Am I using pyment in the wrong way or could it be OS related? 

```
def func(param1=True, param2='default val'):
    '''Description of func with docstring groups style.

    Params:
        param1 - descr of param1 that has True for default value.
        param2 - descr of param2

    Returns:
        some value

    Raises:
        keyError: raises key exception
        TypeError: raises type exception

    '''
    pass

class A:
    def method(self, param1, param2=None):
        pass

if __name__ == "__main__":
    import os
    from pyment import PyComment

    filename = __file__
    print filename

    c = PyComment(filename)
    c.proceed()
    c.diff_to_file(os.path.basename(filename) + ".patch")
    for s in c.get_output_docs():
        print(s)
```

And these are the diff results in the output patch file, which does not convert the Google docstrings the way they do in your README for the same example:

```
# Patch generated by Pyment v0.3.0

--- a/googledoc.py
+++ b/googledoc.py
@@ -1,22 +1,21 @@
 def func(param1=True, param2='default val'):
-    '''Description of func with docstring groups style.
-
-    Params:
-        param1 - descr of param1 that has True for default value.
-        param2 - descr of param2
-
-    Returns:
-        some value
-
-    Raises:
-        keyError: raises key exception
-        TypeError: raises type exception
-
-    '''
+    '''Description of func with docstring groups style.

Params:
        param1 - descr of param1 that has True for default value.
        param2 - descr of param2

    Returns:
        some value

    Raises:
        keyError: raises key exception
        TypeError: raises type exception

+

+    :param param1:  (Default value = True)

+    :param param2:  (Default value = 'default val')

+

+    '''

     pass

 class A:
+    ''' '''

     def method(self, param1, param2=None):
+        '''

+

+        :param param1: 

+        :param param2:  (Default value = None)

+

+        '''

         pass
```

**Comment by dadadel** [comment] 2015-06-02 11:49
Hi @karimbahgat,

I have convetred your example using Pyment v0.3.0 and higher with Python 2.7.6 and 3.4:
```
$ pyment tst.py
```
and I get:
```
# Patch generated by Pyment v0.3.0

--- a/tst.py
+++ b/tst.py
@@ -1,22 +1,24 @@
 def func(param1=True, param2='default val'):
-    '''Description of func with docstring groups style.
+    """Description of func with docstring groups style.

-    Params:
-        param1 - descr of param1 that has True for default value.
-        param2 - descr of param2
+    :param param1: descr of param1 that has True for default value
+    :param param2: descr of param2 (Default value = 'default val')
+    :returns: some value
+    :raises keyError: raises key exception
+    :raises TypeError: raises type exception

-    Returns:
-        some value
-
-    Raises:
-        keyError: raises key exception
-        TypeError: raises type exception
-
-    '''
+    """
     pass

 class A:
+    """ """
     def method(self, param1, param2=None):
+        """
+
+        :param param1: 
+        :param param2:  (Default value = None)
+
+        """
         pass

 if __name__ == "__main__":
```
what seems to be the result expected.
So It could perhaps be OS related, though it sounds strange!

Can you tell me how you use Pyment?
I usually use virtuenv
```
$ virutalenv myenv
$ source myenv/bin/activate
(myenv)$ python setup.py install
# then use 'pyment'
```
But I don't know how it can work under Windows. 

I don't know if it can help but since version v0.3.1, I added JanSchulz fix to setup Pyment using entry_points to get an executable script under Windows.

**Comment by dadadel** [comment] 2017-09-27 21:23
As there is nothing new and the test for the issue is ok, I close this issue.

**Closed by dadadel** 2017-09-27 21:23 UTC
