### ISSUE TITLE
pyment doesn't use my pyment.conf if I don't tell it to do so

### ISSUE THREAD

**Issue by tgy** [dadadel/pyment#29] opened 2017-01-19 11:44 UTC
When running `pyment` from the root of my directory which contains the following `pyment.conf` file

```
first_line = true
quotes = '''
output_style = numpydoc
input_style = numpydoc
init2class = true
```

`pyment` uses the default settings instead.

I don't know if this is expected behavior. On my side I was expecting `pyment` to look for a `pyment.conf` in the current directory, because that's what most programs do when they have a configuration file.

I can submit a PR that does that if it helps!

**Comment by tgy** [comment] 2017-01-19 11:46
I can submit a PR that does that if that can help. 👍

**Comment by dadadel** [comment] 2017-01-19 23:05
Are you still concerned by that problem ? I cannot reproduce it.

**Comment by tgy** [comment] 2017-01-19 23:28
@dadadel yes, from what I read in the code, if no config file is provided pyment will not try to look for a `pyment.conf` config file instead. It just ignores any `pyment.conf` file instead. Maybe I am missing something?

**Comment by dadadel** [comment] 2017-01-20 08:11
Ow! Sorry I didn't get it! 
Indeed @tgy, Pyment won't take into account any configuration file unless it is specified using the appropriate option on the command line. 
By default, Pyment uses hardcoded default values.

**Comment by dadadel** [comment] 2017-01-20 08:12
So, we can consider there is no issue, can't we?

**Comment by tgy** [comment] 2017-01-20 14:38
What I was saying was that Pyment could use the hardcoded string `default_config_file = 'pyment.conf'` to check if `os.path.isfile(default_config_file)` returns `True` and load the config file if that's the case. If this is against your view of what Pyment should be doing you can close the issue.

**Comment by dadadel** [comment] 2017-01-20 14:48
Why not! You can propose a PR if you want.

**Comment by dadadel** [comment] 2017-01-22 16:42
@tgy ^

**Comment by dadadel** [comment] 2021-03-09 13:50
I close this issue. Pyment need to explicitly provide the configuration file. I think it is better to do so.
But feel free to propose a PR if you think it would be better.

**Closed by dadadel** 2021-03-09 13:50 UTC
