### ISSUE TITLE
created patch-file not correct

### ISSUE THREAD

**Issue by theilen** [dadadel/pyment#10] opened 2014-12-03 16:11 UTC
When trying to convert my handwritten docstrings to something more consisting I ran into a corrupted patch-file. I attached a shortened patch-file and the corresponding original file that reproduce the bug. I was using pyment v0.3.0 with Python 2.7.6 (in a WinPython distribution).

1) As you can see, the whole docstring is supposed to be changed to convert `'''` to `"""`. But only the first line of the new docstring is marked with `+`, the other 3 lines are not marked, ergo they are treated as context that should be equal in both files. Therefore the line count of the hunk does not fit anymore and the patching fails.
2) Also note that the last 3 lines got an extra whitespace in the beginning of the line. This is not present in the original file.
3) As a side-note: pyment creates an `a/` and an `b/` in the beginning of the paths of source and target of the patch. Note that these are not the actual folders of the files. I executed pyment in the folder of the file. Comparing with patches created from `diff`, I would guess that you could just omit this behavior.

I do not think it is of importance here, but note that I am using pyment on Windows 7.

**patchfile** (created running `pyment __init__short.py` in the same folder as `__init__short.py`)

``` diff
# Patch generated by Pyment v0.3.0

--- a/__init__ short.py
+++ b/__init__ short.py
@@ -12,12 +12,7 @@


 def init_test():
-    '''
-    Only working when in WinPython root directory.
-    
-    Returns:
-    maske, data0, data1, no_motion, motion
-    '''
+    """Only working when in WinPython root directory.

    Returns:
    maske, data0, data1, no_motion, motion"""

     maske = read_mask('./MRR/Testdaten/55_mask.bmp')
     display(maske)
     data0 = read_dicom_set('./MRR/Testdaten/188_13-12-10_56_1',

```

**original file:**

``` python
# -*- coding: utf-8 -*-

__version__ = '1.3.1'
# $Source$

#Some commentary


from .mod1 import *
#import mod2
from . import mod3, mod4


def init_test():
    '''
    Only working when in WinPython root directory.

    Returns:
    maske, data0, data1, no_motion, motion
    '''
    maske = read_mask('./MRR/Testdaten/55_mask.bmp')
    display(maske)
    data0 = read_dicom_set('./MRR/Testdaten/188_13-12-10_56_1',
                               unwrap=True, mask=maske, verbose=False)
    data1 = read_dicom_set('./MRR/Testdaten/188_13-12-10_54_1',
                               unwrap=True, mask=maske, verbose=False)
    no_motion = mean(data0, axis=0)
    motion = mean(data1, axis=0)
    return maske , data0, data1, no_motion, motion

```

edit: files now reproduce the bug.

**Comment by dadadel** [comment] 2017-01-20 20:22
Hi @theilen,
Do you still have the problem ?
I wasn't able to reproduce with your example.

**Comment by dadadel** [comment] 2017-09-27 21:25
As there is nothing new and the test for the issue is ok, I close this issue.

**Closed by dadadel** 2017-09-27 21:25 UTC
